# -*- coding: utf-8 -*-
"""Task_cellula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBtNrDeYJ_J-BHkws2n7grCa3KydAKVh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

booking_data = {
    "Booking_ID": [f"INN{str(i).zfill(5)}" for i in range(1, 101)],
    "NumberOfAdults": np.random.randint(1, 5, 100),
    "NumberOfChildren": np.random.randint(0, 3, 100),
    "NumberOfWeekendNights": np.random.randint(0, 4, 100),
    "NumberOfWeekNights": np.random.randint(1, 7, 100),
    "MealType": np.random.choice(["Meal Plan 1", "Meal Plan 2", "Not Selected"], 100),
    "RoomType": np.random.choice(["Room_Type 1", "Room_Type 2", "Room_Type 3", "Room_Type 4"], 100),
    "LeadTime": np.random.randint(0, 365, 100),
    "MarketSegmentType": np.random.choice(["Online", "Offline", "Corporate", "Aviation"], 100),
    "AveragePrice": np.random.uniform(50, 300, 100).round(2),
    "BookingStatus": np.random.choice(["Canceled", "Not_Canceled"], 100),
}

#  DataFrame
booking_df = pd.DataFrame(booking_data)

booking_df.dropna(inplace=True)  #removing null values

# Print basic information
print("🔹 First 5 rows of the dataset:\n", booking_df.head(), "\n")
print("🔹 Data Summary:\n", booking_df.describe(include='all'), "\n")
print("🔹 Missing Values:\n", booking_df.isnull().sum(), "\n")
print("🔹 Booking Status Distribution:\n", booking_df["BookingStatus"].value_counts(), "\n")

sns.set_style("whitegrid")

plt.figure(figsize=(8, 5))
sns.countplot(x=booking_df["RoomType"], palette="Blues_r")
plt.title("Room Type Distribution")
plt.xlabel("Room Type")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(booking_df["AveragePrice"], bins=20, kde=True, color="skyblue")
plt.title("Distribution of Average Price")
plt.xlabel("Average Price (USD)")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x=booking_df["BookingStatus"], palette="Set2")
plt.title("Count of Canceled vs. Not Canceled Bookings")
plt.xlabel("Booking Status")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(data=booking_df, x="RoomType", hue="BookingStatus", multiple="stack", palette="coolwarm")
plt.title("Booking Status by Room Type")
plt.xlabel("Room Type")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

# Grouped bar chart for Booking Status per Market Segment
plt.figure(figsize=(10, 6))
sns.countplot(data=booking_df, x="MarketSegmentType", hue="BookingStatus", palette="muted")
plt.title("Booking Status by Market Segment Type")
plt.xlabel("Market Segment Type")
plt.ylabel("Count")
plt.legend(title="Booking Status")
plt.xticks(rotation=30)
plt.show()