# Generated by Django 5.1.7 on 2025-03-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellula_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('number_of_weekend_nights', models.IntegerField()),
                ('number_of_week_nights', models.IntegerField()),
                ('type_of_meal', models.CharField(max_length=100)),
                ('car_parking_space', models.BooleanField()),
                ('room_type', models.CharField(max_length=100)),
                ('lead_time', models.IntegerField()),
                ('market_segment_type', models.CharField(max_length=100)),
                ('repeated', models.BooleanField()),
                ('p_c', models.IntegerField()),
                ('p_not_c', models.IntegerField()),
                ('average_price', models.FloatField()),
                ('special_requests', models.IntegerField()),
                ('date_of_reservation', models.DateField()),
                ('booking_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
