# Generated by Django 5.1.7 on 2025-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellula_app', '0002_booking_delete_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_reservation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
