# Generated by Django 4.2.20 on 2025-03-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RideData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=100)),
                ("driver_name", models.CharField(max_length=100)),
                ("car_condition", models.CharField(max_length=50)),
                ("weather", models.CharField(max_length=50)),
                ("traffic_condition", models.CharField(max_length=100)),
                ("fare_amount", models.FloatField()),
                ("pickup_datetime", models.DateTimeField()),
                ("pickup_longitude", models.FloatField()),
                ("pickup_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("distance", models.FloatField()),
                ("bearing", models.FloatField()),
            ],
        ),
    ]
